### ISSUE TITLE
Version Page is Blank

### ISSUE THREAD

**Issue by athreadgill** [lukasbestle/kirby-versions#13]
I installed the plugin and ran all the git commands with no issue but when I go to the versions page it is just blank with no errors. I get no errors in the log either.

Kirby Version 3.8.2 PHP 8.1.9 on Nginx server.

**Comment by lukasbestle** [comment]
Could you please post a screenshot of the Versions view?

**Comment by athreadgill** [comment]
![image](https://user-images.githubusercontent.com/66741090/205652104-4e309ca8-402d-42a1-91af-4ab1753a9a86.png)

**Comment by lukasbestle** [comment]
Is there not even the Panel topbar? Do you see anything in the browser console when you switch from the Panel dashboard to the Versions view?

**Comment by athreadgill** [comment]
No there isn't anything in the panel topbar.

![image](https://user-images.githubusercontent.com/66741090/205945384-1c835f86-c33c-469f-baea-124e428ae152.png)

**Comment by lukasbestle** [comment]
Could you please post the HTML source code you get when you reload `/panel/versions`? Please ensure that no sensitive information is contained, you can of course anonymize that.

**Comment by lukasbestle** [comment]
Thanks for that, the output looks as expected. It's very weird that you only get a blank page without any errors.

Have you tried:

- clearing your cache,
- using a different browser (which one?),
- installing the plugin to a Kirby Starterkit?

**Comment by athreadgill** [comment]
To verify git should be running on the content folder only?

**Comment by lukasbestle** [comment]
That's certainly the setup I'd test first as it's also the one this plugin was built for and tested with.

**Comment by lukasbestle** [comment]
@athreadgill Have you been able to reproduce the issue?

**Comment by lukasbestle** [comment]
I'm closing the issue for now. If you can reproduce the issue again, please let me know, ideally with reproduction steps.
