### ISSUE TITLE
Docs enhancement (Wiki)

### ISSUE THREAD

**Issue by hariom147** [lukasbestle/kirby-versions#14]
Hi Lukas, 
thank you for making this great plugin.

While following the docs, I noticed that for someone who is a beginner with git, this instruction might be confusing:

>**Important**: Please now verify using the search function of your terminal (Ctrl/Cmd F) that no .lock file was added, 

I suggest the following edit:

>**Important**: Please now verify that no `.lock` file was added by listing the added files. Enter `git status` in your terminal and then use the search function of your terminal (`Ctrl`/`Cmd` `F`) to be sure no `.lock`files were added, since that would break the plugin's behavior later.

(I would have made a PR, but Wikis don't get forked...)

**Comment by lukasbestle** [comment]
Thanks for your feedback. 👍

Running `git status` should not be necessary though because `git add` also lists the files it adds. Or didn't it do that for you?

**Comment by hariom147** [comment]
> Or didn't it do that for you?

No, it didn't and doesn't in general when I use git in terminal. But now that you mention it, it totally makes sense...

Although I never (consciously) changed any git settings in that regard...
