### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [lukasbestle/kirby-versions#16]
> The installed version of the Kirby Versions plugin is not compatible with Kirby 4.0.0-rc.4

Kirby 4.0.0-rc.4
PHP 8.1.23

**Comment by lukasbestle** [comment]
For everyone reading along: I will update my plugins for Kirby 4 in the next few days. 🙂

**Comment by lukasbestle** [comment]
I admit it took a lot longer than a few days, but there are now finally releases of the Versions plugin to support Kirby 3.10 and 4.0. Sorry for the huge delay, there was a lot going on.
