### ISSUE TITLE
Kirby 3.7.0 compatibility

### ISSUE THREAD

**Issue by renestalder** [lukasbestle/kirby-versions#8]
The plugin currently blocks installation via composer on Kirby 3.7.0 per version range. Is that intentional or could that be changed?

**Comment by lukasbestle** [comment]
It's intentional, but I'm already working on an update. :)

**Comment by lukasbestle** [comment]
Sorry for the delay. The work on the Kirby core (3.7.1 and 3.8) has consumed most of my time in the last weeks. I hope I'll get the update done this week.

**Comment by lukasbestle** [comment]
✅ Fixed with the new plugin release 1.0.3.
